### ISSUE TITLE
Unusable README file

### ISSUE THREAD

**Issue by cmatthewbrooks** [deepbindiff/DeepBinDiff#1]
The README file offers zero information about how to actually use or evaluate this code base nor does it provide any information on system/environment requirements.

**Comment by yueduan** [comment]
thanks. I have been super busy recently. I will update the readme as well as cleanup the code to make it more readable as soon as I can. Stay tuned!

**Comment by jibanes** [comment]
hello yueduan, I'd also like to try it.

**Comment by yueduan** [comment]
Thanks for your interest. I am almost done with my current task. I will try to update the readme and cleanup the code recently. Stay tuned!

**Comment by jibanes** [comment]
Thank you very much Yueduan; please also provide some complete but simple examples on how to operate it.

**Comment by deepbindiff** [comment]
README updated! Enjoy~
