### ISSUE TITLE
Why this code cannot run in GPU

### ISSUE THREAD

**Issue by yanyuLinxi** [deepbindiff/DeepBinDiff#10]
Dear sir or Madam,
        When I run this code, it shows that the code can only run on the cpu. But the model running on the cpu took too much time. I want to know which part of the code makes the model unable to run on the cpu and whether it can be transplanted to the gpu to run. Thank you with my greatest respect.

**Comment by yueduan** [comment]
Hi, as mentioned in README, this code is meant to run on CPU only. If you want to use GPU to run, you would need to modify buildAndTraining() function in featureGen.py. The specifical line you want to explore is Line 263.
