### ISSUE TITLE
How to input half of the binaries into the model training

### ISSUE THREAD

**Issue by yanyuLinxi** [deepbindiff/DeepBinDiff#11]
Hi, i am trying to run this code in a server, but the result is not good. I have noticed that there is a sentence in the paper: "We randomly select half of the binaries in our dataset for token embedding model training", but i cannot find a function in this code to load half of binaries of a dataset  in one-time. Do i miss any important details? Or this code can only run two binary in one-time?

**Comment by yueduan** [comment]
Hi, this version of the code only takes as input two binaries. Therefore, the model is trained on-the-fly. If you want to pre-train a model, you would need to make modifications to the code. I may make this change in the future as well.
