### ISSUE TITLE
Problem About the Source Code

### ISSUE THREAD

**Issue by XX-Official** [deepbindiff/DeepBinDiff#12]
Thanks for your outstanding work, but I met some problems with your source code.
In preprocessing.py ，

def offsetStrMappingGen(cfg1, cfg2, binary1, binary2, mneList):
    # count type of constants for feature vector generation
    
    # offsetStrMapping[offset] = strRef.strip()
    offsetStrMapping = {}

    # lists that store all the non-binary functions in bin1 and 2
    externFuncNamesBin1 = []
    externFuncNamesBin2 = []

    for func in cfg1.functions.values():
        if func.binary_name == binary1:
            for offset, strRef in func.string_references(vex_only=True):
                offset = str(offset)
                #offset = str(hex(offset))[:-1]
                if offset not in offsetStrMapping:
                    offsetStrMapping[offset] = ''.join(strRef.split())
        elif func.binary_name not in externFuncNamesBin1:
            externFuncNamesBin1.append(func.name)
                     
def externBlocksAndFuncsToBeMerged(cfg1, cfg2, nodelist1, nodelist2, binary1, binary2, nodeDic1, nodeDic2, externFuncNamesBin1, externFuncNamesBin2, string_bid1, string_bid2):
    # toBeMerged[node1_id] = node2_id
    toBeMergedBlocks = {}
    toBeMergedBlocksReverse = {}

    # toBeMergedFuncs[func1_addr] = func2_addr
    toBeMergedFuncs = {}
    toBeMergedFuncsReverse = {}
    
    externFuncNameBlockMappingBin1 = {}
    externFuncNameBlockMappingBin2 = {}
    funcNameAddrMappingBin1 = {}
    funcNameAddrMappingBin2 = {}

    for func in cfg1.functions.values():
        binName = func.binary_name
        funcName = func.name
        funcAddr = func.addr
        blockList = list(func.blocks)
                
        if (binName == binary1) and (func.name in externFuncNamesBin1) and (len(blockList) == 1):
            for node in nodelist1:
                if (node.block is not None) and (node.block.addr == blockList[0].addr):     
                    externFuncNameBlockMappingBin1[funcName] = nodeDic1[node]
                    funcNameAddrMappingBin1[funcName] = funcAddr

The non-binary functions are stored in **externFuncNamesBin1**, whose binary names are not binary1.  And when it goes to 
`if (binName == binary1) and (func.name in externFuncNamesBin1) and (len(blockList) == 1):`, the condition will never be satisfied.

**Comment by yueduan** [comment]
Hi, thanks for your feedback. Are you sure the binary name is not 'binary1'? I think it should be.

**Comment by XX-Official** [comment]
> Hi, thanks for your feedback. Are you sure the binary name is not 'binary1'? I think it should be.
If the  non-binary functions' binary name is 'binary1',  
`for func in cfg1.functions.values():
    if func.binary_name == binary1:
        for offset, strRef in func.string_references(vex_only=True):
            offset = str(offset)
            #offset = str(hex(offset))[:-1]
            if offset not in offsetStrMapping:
                offsetStrMapping[offset] = ''.join(strRef.split())
    elif func.binary_name not in externFuncNamesBin1:
        externFuncNamesBin1.append(func.name)`
I think this condition can not distinguish the non-binary functions.
