### ISSUE TITLE
requirements.txt?

### ISSUE THREAD

**Issue by katshup** [deepbindiff/DeepBinDiff#2]
Hey, I would love to get this up and running. It would seem though that I’m using an incorrect version of TensorFlow though. 

I think having a requirements.txt would make installation easier.

**Comment by yueduan** [comment]
Hi, thanks for your interest. I am really busy recently. I will write a much better readme about the required environment and how to run the tool as soon as I can. Stay tuned!

**Comment by deepbindiff** [comment]
README updated! Enjoy~
