### ISSUE TITLE
IDA or Angr?

### ISSUE THREAD

**Issue by zzh-z** [deepbindiff/DeepBinDiff#3]
I want to run deepbindiff and have read some of your codes. 
It seems deepbindiff leverages Angr to extract basic block information and generate CFG instead of IDA?

**Comment by yueduan** [comment]
Hi, we have both the IDA pro version and the angr version. IDA pro is used in order to directly compare with BinDiff, which uses IDA pro as well. The one I uploaded uses Angr indeed. Thanks.
