### ISSUE TITLE
How to deal with instructions with different number of address

### ISSUE THREAD

**Issue by seekamoon** [deepbindiff/DeepBinDiff#7]
Nice work.
However, there are also some questions about the instruction embedding. I hope to get your answer.

The practice of instruction embedding in your paper is the opcode times TF-IDF weight, and concat the average of operands. For example, if the dimension of a single opcode or operand is 64, the final dimension of instruction is 64+64=128 (I hope I understand correctly).

However, there are some opcode with none operand such as 'retn', 'pusha', 'popa', 'cdq', etc. How did you deal with such instructions? Ignore or concat a zero embedding as operands?

Thanks.

**Comment by yueduan** [comment]
Hi Thanks for your interest. We concat a zero embedding as operands in this case.

**Comment by seekamoon** [comment]
Ok, I get it now. Thank you for your prompt reply.
